### PR TITLE
[issue-234] Fix TLS security configurations

### PR DESCRIPTION
**Pull request by vijikarthi**
Signed-off-by: Vijay Srinivasaraghavan <vijayaraghavan.srinivasaraghavan@emc.com>

**Change log description**
  * Updated security configurations to sync with Pravega

**Purpose of the change**
To address https://github.com/pravega/flink-connectors/issues/234

**What the code does**
Uses security configurations from Pravega based on changes introduced in pravega/pravega#3693 and uses these artifacts to run security enabled Pravega integration tests

**How to verify it**
./gradlew clean build should pass

### CODE REVIEW

**Comment by vijikarthi** [comment]
> A test has failed in the Travis CI build, which seems to be unrelated to the PR. It should be fixed before the PR is merged. Otherwise, the changes look good to me.

Yes it is expected and it will be addressed with thir PR https://github.com/pravega/flink-connectors/pull/238

**Comment by vijikarthi** [comment]
I am not sure how to change this PR to `draft` since I want to merge this PR only after all other PRs are merged.

**Comment by fpj** [comment]
@vijikarthi can you fix the conflict, please?

**Comment by vijikarthi** [comment]
> @vijikarthi can you fix the conflict, please?

I have now reverted the Pravega version and will create a separate PR to handle the Pravega version update.

**Pull request merged**
