### PR TITLE
[Issue-450] Update pravega client to 0.9.0-2765

### LINKED ISSUE #450: Update Pravega client to the latest 0.9
**Problem description**
- Update Pravega client to 0.9.0-2765.79a6eb7-SNAPSHOT
- Update Pravega submodule to commit 79a6eb7

**Problem location**
gradle settings and submodule

**Suggestions for an improvement**

### PR DESCRIPTION
**Pull request by pavanbhat21**
**Change log description**
- Update Pravega client to latest 0.9

**Purpose of the change**
Fixes #450 

**What the code does**
- Update Pravega client to `0.9.0-2765.79a6eb7-SNAPSHOT`
- Update Pravega submodule to commit `79a6eb7`

**How to verify it**
`./gradlew clean build` passes

### CODE REVIEW

**Comment by maddisondavid** [comment]
This updates the Gradle build but looks like the Pravega submodule needs updating to commit `79a6eb7`

**Comment by claudiofahey** [comment]
FYI, the following test on Travis is failing.
```
Test testPravegaSourceSink(io.pravega.connectors.flink.dynamic.table.FlinkPravegaDynamicTableITCase) failed with:
java.lang.AssertionError: expected:<[+I(2019-12-12 00:00:05.000,2019-12-12,00:00:03,2019-12-12 00:00:04.004,3,50.00), +I(2019-12-12 00:00:10.000,2019-12-12,00:00:05,2019-12-12 00:00:06.006,2,5.33)]> but was:<[+I(2019-12-12 00:00:05.000,2019-12-12,00:00:02,2019-12-12 00:00:03.002,2,2.02), +I(2019-12-12 00:00:10.000,2019-12-12,00:00:05,2019-12-12 00:00:06.006,2,5.33)]>
```
It is unclear if this is due to the Pravega client update or a pre-existing problem. I have kicked off another build on Travis as well as my local PC.

**Comment by claudiofahey** [comment]
The test failure appears to be caused by a faulty test, not by this PR.

**Review by claudiofahey — APPROVED** [review]

**Comment by claudiofahey** [comment]
@pavanbhat21, you will need to sign your last commit to get the DCO check to pass.

**Comment by claudiofahey** [comment]
The integration test FlinkPravegaDynamicTableITCase continues to fail, even after adding retries to the read portion of the test with a timeout of 2 minutes. This indicates some other problem with this test.
```
2021-02-16 01:13:29,750 1200819 [Time-limited test] INFO  i.p.c.f.d.t.FlinkPravegaDynamicTableITCase - Retrying read query. expected=[+I(2019-12-12 00:00:05.000,2019-12-12,00:00:03,2019-12-12 00:00:04.004,3,50.00), +I(2019-12-12 00:00:10.000,2019-12-12,00:00:05,2019-12-12 00:00:06.006,2,5.33)], actual=[+I(2019-12-12 00:00:05.000,2019-12-12,00:00:02,2019-12-12 00:00:03.002,2,2.02), +I(2019-12-12 00:00:10.000,2019-12-12,00:00:05,2019-12-12 00:00:06.006,2,5.33)]
```

**Review by shrids — APPROVED** [review]

**Pull request merged**
